### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt6.QtWebEngineCore'

### ISSUE THREAD

**Issue by zeitchef** [keiqu/inka#136]
I'm not exactly sure what to do here. I've tried `python3 pip -m install PyQtWebEngine` but it's not being found (or is only for PyQt5?). Not sure which version of PyQT is being targeted here TBH.

<img width="816" alt="Screenshot 2022-11-16 at 17 17 52" src="https://user-images.githubusercontent.com/6670659/202235913-1fe3a61f-d460-4d79-af17-8c3c390293e5.png">

Any tips would be appreciated!

**Comment by keiqu** [comment]
Hi, I will look into it today.

**Comment by zeitchef** [comment]
Sorry to bump this, but any news here? I'm running around in circles, reinstalling python versions and experimenting with alternative package managers to no avail.

**Comment by keiqu** [comment]
Don't be sorry. Almost done fix two weeks ago but irl issues emerged and I completely forgot to finish it. 

The issue itself is in new Anki dependencies. Bumped them for new version `2.2.1` which should work fine.

**Comment by zeitchef** [comment]
Great!
