### ISSUE TITLE
Allow customization of delimiter strings

### ISSUE THREAD

**Issue by harvastum** [keiqu/inka#85]
It would be nice to be able to use something else than `---` as cards delimiters.
For example, I think it would be more elegant to have something like
````
```inka
<card contents>
```
````

Sometimes this is a matter of preference, but it would be very useful if you want to embed Anki cards in file with some potentially conflicting content, or if someone already has notes made with another parser in mind.

**Comment by keiqu** [comment]
I will think about it. From what I remember about code base, it won't be that easy to implement. And I don't have all that much time at the moment to do it.

**Comment by keiqu** [comment]
not  gonna be done
