### ISSUE TITLE
Include a default config.ini file in the PyPI package

### ISSUE THREAD

**Issue by harvastum** [keiqu/inka#86]
Currently, there is no config.ini shipped in the package available on PyPI. Running `inka config --reset` is required to create one with defaults, which is not obvious and not mentioned in the readme.

**Comment by keiqu** [comment]
Yes, it is not shipped. But if no config found, app creates new one with default settings. So running `inka config --reset` is not required.

**Comment by keiqu** [comment]
Nah. I don't really see point in this. Although I added a line in config wiki page, that mentions that config file automatically created if missing.
