### ISSUE TITLE
Feature request: support for Asciidoc as a source

### ISSUE THREAD

**Issue by bybor** [keiqu/inka#93]
Could you consider implementing it?

If not, could you draft what is needed for it, i.e. how hard it is to do.

I hope that right now it is about converting markdown into html with some magic around 'cloze' expressions (to generate multiple cards). I'm pretty sure there is more to it, would be great to learn the key points of transformation.

Right now I use asciidoctor + pandoc (docbook as intermediary format). It works, but it makes editing source notes a bit complicated.

But, even with this approach I get remarkable results.

Thank you for Inka!

**Comment by keiqu** [comment]
Actually current implementation is not tied to Markdown. I didn't implement a "proper" parsing. It's just a bunch of regular expressions that look for the blocks of text of the desired format (which specified in a readme). The current `.md`/`.markdown` file extension restriction only serves the purpose of reducing the number of files processed if you specify a directory containing files in other non-Markdown formats (images, videos, etc.). 

You can give me an example of an Asciidoc file with cards to check that everything is working correctly. But it seems to me that the only change that is needed here is to add a config option in which you can set a list of "allowed" file extensions.

**Comment by bybor** [comment]
Thank you, I didn't realize it.

I think it will not work in my use case - it's very artificial, but still. Your markdown implementation works very well in my tool chain (asciidoctor -> docbook -> pandoc -> md -> inka), so I have a full support for whatever I want to write in Asciidoc.

I will close this issue, it doesn't look very relevant.

Of things that I use:

- asciidoc uses a different style for code blocks. It kind of supports MD style (in the form of a line with leading spaces, but w/o syntax highlighting)
- I use asciimath because I don't know LaTeX.
- there is no need to specify numbers in numbered list.

It's a matter of personal preference, I understand that I can write Markdown and use some converters for math. 

Here is an example.

```
---

DECK: Default

. If the function is differentiable, then the necessary condition for the extremum of the function is {{c1::asciimath:[f^'(x) = 0]}}.

. Get elements of list `lst` with 7 elements in reverse order {
[source, python]
----
lst = [10, 20, 30, 40, 50, 60, 70]
lst[-1:-8:-1]
----
}

---
```

Thank you!

**Comment by keiqu** [comment]
Hm, I was incorrect when I said that inka not tied to Markdown. The simplified version of inka's pipeline is: 
find block of cards in file -> find separate cards in that block -> convert their text from markdown to html -> add result to Anki.

And to add support for asciidoc, you need to add separate implementations for steps 2 and 3. Step 2 should be easy from an implementation point of view, but writing tests can be time consuming. And step 3 requires some sort of asciidoc->html python library, since I'm not ready to write one myself.

**Comment by bybor** [comment]
Thank you, it makes sense!

There are asciidoc-py (legacy) and https://www.asciidoc3.org/ , but I didn't use any of them. Original asciidoc was Python2, which is no longer relevant.

Thanks again!
